version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    restart: always
    ports:
      - "5445:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks: [homework_fastapi]

volumes:
  postgres_data:

networks:
  homework_fastapi:
    name: fastapi